import { snakeCase } from 'change-case';
import { Declaration, Eol, Line } from './syntax/common';

const logo = `/*

     ________  ________  ________           ________  _______   ________      
    |\\   __  \\|\\   __  \\|\\   ____\\         |\\   ____\\|\\  ___ \\ |\\   ___  \\    
    \\ \\  \\|\\  \\ \\  \\|\\  \\ \\  \\___|_        \\ \\  \\___|\\ \\   __/|\\ \\  \\\\ \\  \\   
     \\ \\  \\\\\\  \\ \\   __  \\ \\_____  \\        \\ \\  \\  __\\ \\  \\_|/_\\ \\  \\\\ \\  \\  
      \\ \\  \\\\\\  \\ \\  \\ \\  \\|____|\\  \\        \\ \\  \\|\\  \\ \\  \\_|\\ \\ \\  \\\\ \\  \\ 
       \\ \\_______\\ \\__\\ \\__\\____\\_\\  \\        \\ \\_______\\ \\_______\\ \\__\\\\ \\__\\
        \\|_______|\\|__|\\|__|\\_________\\        \\|_______|\\|_______|\\|__| \\|__|
                           \\|_________|                                       
       
						
               PLEASE DO NOT EDIT THIS FILE! IT HAS BEEN GENERATED AND          
                        ALL YOUR CHANGES CAN BE OVERWRITTEN.                     

*/
`;

export const Document: JSXTE.Component<{ name: string }> = ({ children, name }) => {
	const includedKey = `_${snakeCase(name)}_included`;
	return (
		<Declaration>
			{logo}
			<Eol />
			<Line>#if defined {includedKey}</Line>
			<Line>#endinput</Line>
			<Line>#endif</Line>
			<Line>#define {includedKey}</Line>
			<Eol />
			<Line>{'#include <amxmodx>'}</Line>
			<Line>{'#include <easy_http>'}</Line>
			<Eol />
			{children}
		</Declaration>
	);
};
