const logo = `/*

     ________  ________  ________           ________  _______   ________      
    |\\   __  \\|\\   __  \\|\\   ____\\         |\\   ____\\|\\  ___ \\ |\\   ___  \\    
    \\ \\  \\|\\  \\ \\  \\|\\  \\ \\  \\___|_        \\ \\  \\___|\\ \\   __/|\\ \\  \\\\ \\  \\   
     \\ \\  \\\\\\  \\ \\   __  \\ \\_____  \\        \\ \\  \\  __\\ \\  \\_|/_\\ \\  \\\\ \\  \\  
      \\ \\  \\\\\\  \\ \\  \\ \\  \\|____|\\  \\        \\ \\  \\|\\  \\ \\  \\_|\\ \\ \\  \\\\ \\  \\ 
       \\ \\_______\\ \\__\\ \\__\\____\\_\\  \\        \\ \\_______\\ \\_______\\ \\__\\\\ \\__\\
        \\|_______|\\|__|\\|__|\\_________\\        \\|_______|\\|_______|\\|__| \\|__|
                           \\|_________|                                       
       
						
               PLEASE DO NOT EDIT THIS FILE! IT HAS BEEN GENERATED AND          
                        ALL YOUR CHANGES CAN BE OVERWRITTEN.                     

*/
`

export const Document: JSXTE.Component<{ name: string }> = ({ children, name }) => {
     return (
          <>
               {logo}

               #if defined _{name}_included
               #endinput
               #endif
               #define _{name}_included

               {'#include <amxmodx>'}
               {'#include <easyhttp>'}

               {children}
          </>
     )
}